name: update

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
   - cron:  '0 */3 * * *'

jobs: 
  scrap_data:
    # The type of runner that the job will run on
    runs-on: macos-latest

    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

    # Load repo and install R
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@master

    # Set-up R
    - name: Install packages
      run: |
        R -e 'install.packages(c("rtweet", "stringr", "here", "tesseract", "magick"))'
    # Run R script
       #  - name: scrapUN
       #  run: Rscript script/scrapUN.R
      # Run R script
    - name: scrapRussianLosses
      run: Rscript script/scrapRussianLosses.R
      # Run R script
    - name: scrapProsecutorGeneral
      run: Rscript script/scrapProsecutorGeneral.R
     
 # Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      run: |
          echo "Checking data on: `date`"
          if [ -n "$(git status --porcelain)" ]; then
            echo "New update available"
            git config --local user.name actions-user
            git config --local user.email "actions@github.com"
            git add data/*
            git commit -am "Update data - $(date)"
            git push origin main
          else
            echo "no changes to commit"
          fi
      env:
        TZ: Europe/Rome
